version: '3.1'
services:
  mysql:
    container_name: "payment_db"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
      MYSQL_DATABASE: payment
    restart: on-failure
  redis:
    container_name: "payment_session_store"
    image: redis
    ports:
      - "6379:6379"
  server:
    depends_on:
      - mysql
      - redis
    container_name: "payment_server"
    build: .
    ports:
      - "5000:5000"
    command: yarn fast-start
    environment:
      PORT: 5000
      DATABASE_NAME: payment
      DATABASE_HOST: mysql
      DATABASE_ID: payment
      DATABASE_PW: payment

      REDIS_HOST: redis
    restart: on-failure
    links:
      - redis
      - mysql